name: zeronet
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 2.1.0
  archive: 2.0.11
  crypto: 2.1.3
  device_info: 0.4.1+3
  file_picker: 1.4.3+2
  flutter_absolute_path: 
    path: ../flutter_absolute_path
    # git:
    #   url : https://github.com/canewsin/flutter_absolute_path.git
  flutter_downloader: 1.4.1
  flutter_mobx: 0.3.3+3
  http: 0.12.0+3
  mobx: 0.3.3+1
  package_info: 0.4.0+12
  path_provider: 1.5.0
  random_string: 2.0.1
  url_launcher: 5.2.7
  flutter_webview_plugin: 0.3.10+1
  flutter_local_notifications: ^1.1.6
    # git:
    #   url: https://github.com/canewsin/flutter_local_notifications
    #   ref: actions
  web_socket_channel: 1.1.0
  zeronet_ws:
    path: ../zeronet_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.3+1
flutter:
  uses-material-design: true
  assets:
    - assets/